DATABASE_SCHEMA = """
Database: DuckDB

Only these tables may be queried.

========================================
Table: silver_orders
========================================

Columns:
- order_id
- customer_id
- product_id
- product_name
- region
- unit_price
- quantity
- order_total
- event_timestamp
- ingested_at

Description:
Contains all cleaned customer orders.

========================================
Table: alerts
========================================

Columns:
- alert_id
- alert_timestamp
- severity
- region
- alert_type
- reason

Description:
Contains anomaly alerts generated by the pipeline.

Possible alert_type values:
- high_value_order
- data_quality

Possible severity values:
- info
- warning

Important:
High-value order alerts are identified by:

alert_type = 'high_value_order'

NOT by severity.

Severity only indicates importance (info/warning).
"""
